### ISSUE TITLE
`program.command` is a method name

### ISSUE THREAD

**Issue by rhalff** [flowbased/fbp-protocol#1]
`program.command` is a method name in [commander.js](https://github.com/tj/commander.js)

```
fbp-init --name chix-runtime --collection test
Stored the following configuration to /home/ubuntu/workspace/fbp-config.json

name: chix-runtime
command: function (name, desc) {
  var args = name.split(/ +/);
  var cmd = new Command(args.shift());

  if (desc) {
    cmd.description(desc);
    this.executables = true;
    this._execs[cmd._name] = true;
  }

  this.commands.push(cmd);
  cmd.parseExpectedArgs(args);
  cmd.parent = this;

  if (desc) return this;
  return cmd;
}
host: localhost
port: 8080
collection: test

To test, run `fbp-test` from this directory
```

Easiest fix will be to change the name for the `--command` option.

`run` or `exec` maybe?

or else use a different cli tool.

update:
I guess command could still be used, just beware if no command option is passed the value will not be empty.

**Comment by chadrik** [comment]
Honestly, I'm a bit appalled by that design.  There should at least be an alternate way to access protected values, like `program.parsed.command`.  Anyway, I hacked around this by forcing `program.command = null`, since we don't need this function.  I like the name `command` the best, as it is a noun, like all of the other options, whereas `run` and `exec` are both verbs.
