### ISSUE TITLE
Add a test using fbp-spec

### ISSUE THREAD

**Issue by jonnor** [flowbased/fbp-protocol#5]
fbp-spec exercises the FBP protocol implementation of a runtime quite a lot, and is generally useful, so we could include it here.

A testcase for core/Repeat (like
https://github.com/flowbased/fbp-spec/blob/master/examples/simple-passing.yaml)
but covering all JSON types would be a really good start.

It can be trivally integrated with Mocha like this https://github.com/flowbased/fbp-spec/blob/master/spec/mocha.coffee

**Comment by chadrik** [comment]
I've been wondering if it wouldn't be better to merge these two repos. It's
unclear from the docs what the difference between them is. What's the
advantage of keeping them separated?

**Comment by jonnor** [comment]
They serve different purposes:

* `fbp-protocol` is tests for a the implementation of the FBP runtime protocol. Primarily used by people who develop an FBP runtime.
* `fbp-spec` is a testing tool for FBP components, graphs and systems (in a BDD/data-driven way). Mostly used by component/library and application developers.

It is not the purpose of fbp-spect to test the FBP runtime protocol implementation. But because it uses the protocol heavily it adds some coverage as a side-effect.

There is also no shared code between the two projects, so I don't see any reason to merge them...

**Comment by jonnor** [comment]
@chadrik did my explanation above make sense?

**Comment by chadrik** [comment]
I see how those are two different use-cases, but I disagree that they are so different as to require separate repos.  If testing my components requires that the FBP protocol is properly implemented by my runtime, than to me it makes sense that testing the protocol be part of a my tests.  Otherwise errors might occur that appear to be my component's fault when in fact they are at the protocol level.  And if this ticket is in indicated that we're considering adding a test from what was supposed to be the higher-level repo into the lower-level one, than I think that circularity confirms that these two repos should be one.

As an outsider getting started with noflo I found the number of inter-related and similarly named repos in the noflo project bewildering, and I still do.  I don't think we should repeat that here.  I think we should have just one repo for testing everything together at once, which also has the ability to run particular test cases, as any test runner would.   If that means folding `fbp-protocol` into `fbp-spec`, then great.  We should then update the readme to give a concise high-level explanation of the test suites available and who should use them.

my 2 c.

**Comment by jonnor** [comment]
A goal is that application developers don't need to install and run things which the developer of runtime uses to ensure the runtime/protocol implementation is correct. One cannot expect app devs to run

fbp-spec is also a fairly unproved testing concept (declarative, data-driven, multi-runtime). We've already had several testing tools/projects in NoFlo which have more-or-less failed. I don't want to pollute fbp-protocol code with such experimental things (calling `fbp-spec` as a command-line program would be a very loose coupling compared to merging codebases).

**Comment by jonnor** [comment]
Anyway, we can close this issue as a wont-fix. Runtime developers who find `fbp-spec` to be a useful tool in verifying their FBP protocol implementation can then use it directly instead of through `fbp-protocol` (or not).
